name: Build Winx Browser

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install UPX
        run: choco install upx -y

      - name: Build exe
        run: |
          pyinstaller --onefile --console --uac-admin --icon "icon.ico" `
            --upx-dir "C:\ProgramData\chocolatey\bin" `
            --name "Winx Browser" `
            --hidden-import mitmproxy `
            --hidden-import mitmproxy.proxy `
            --hidden-import mitmproxy.proxy.server `
            --hidden-import mitmproxy.tools `
            --hidden-import mitmproxy.tools.dump `
            --hidden-import mitmproxy.addons `
            --hidden-import mitmproxy.options `
            --hidden-import mitmproxy.http `
            --hidden-import mitmproxy.certs `
            --hidden-import pystray `
            --hidden-import PIL `
            --hidden-import PIL.Image `
            --hidden-import PIL.ImageDraw `
            --hidden-import requests `
            --hidden-import winreg `
            --hidden-import shutil `
            --hidden-import proxy `
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinxBrowser
          path: dist/Winx Browser.exe
