name: Build Winx Browser

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build exe
        run: pyinstaller --onefile --noconsole --uac-admin --icon "icon.ico" --name "Winx Browser" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WinxBrowser
          path: dist/Winx Browser.exe
